version: "3"  # Actualización de la versión

services:
  app:
    container_name: lookcut
    build: .
    ports:
      - "8082:8082"  # Reenvío del puerto 8082 para la app
      - "5555:5554"  # Reenvío del puerto 5544 para la comunicación ADB
    privileged: true
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
  db:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres

volumes:
  app_data: